---
name: lein_test

on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read


jobs:
  run-lein-tests:
    name: lein test - Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21', '25' ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup java
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@4c7a6f613e5089821bb3bb2a33a3ee115578580d # 13.6.1
        with:
          cli: latest              # Clojure CLI based on tools.deps
          lein: latest                  # Leiningen
          boot: latest                  # Boot.clj
          bb: latest                    # Babashka
          clj-kondo: latest        # Clj-kondo
          cljstyle: latest             # cljstyle
          zprint: latest                # zprint
      - name: Run lein tests with dev profile
        run: lein with-profile dev test
        env:
          FIPS: false
      # To be fixed soon - disabling until it is resolved
      #- name: Run lein tests with fips profile
      #  run: lein with-profile fips test
      #  env:
      #    FIPS: true

  tests:
    if: always()
    needs:
      - run-lein-tests
    runs-on: ubuntu-24.04
    name: Test suite
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
